#aws
cloud:
  aws:
    s3:
      bucket: woowa-ioi
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: # https://woowacourse.slack.com/archives/CFE64TG1X/p1566115394191400 참고
      secretKey: # https://woowacourse.slack.com/archives/CFE64TG1X/p1566115394191400 참고